{ created_at: 'Sun Jun 12 14:15:55 +0000 2016',
  id: 741997465008635900,
  id_str: '741997465008635904',
  text: 'Follow the top Ember.js stories for Jun 12 on our topical page: https://t.co/Co0SyEd9QB',
  truncated: false,
  entities:
   { hashtags: [],
     symbols: [],
     user_mentions: [],
     urls: [ [Object] ] },
  source: '<a href="https://www.emberjstops.com/app" rel="nofollow">TopEmber.JsNews</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
   { id: 3875615054,
     id_str: '3875615054',
     name: 'Ember.js Top News',
     screen_name: 'EmberJSTopNews',
     location: '',
     description: 'Follow us for the top Ember.Js news, curated by the Twitter community.',
     url: 'https://t.co/4rpyUmUoRU',
     entities: { url: [Object], description: [Object] },
     protected: false,
     followers_count: 893,
     friends_count: 4899,
     listed_count: 22,
     created_at: 'Tue Oct 13 01:46:36 +0000 2015',
     favourites_count: 317,
     utc_offset: null,
     time_zone: null,
     geo_enabled: false,
     verified: false,
     statuses_count: 815,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_image_url: 'http://pbs.twimg.com/profile_images/653748913774592001/HxVFUEKl_normal.png',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/653748913774592001/HxVFUEKl_normal.png',
     profile_link_color: '0084B4',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     has_extended_profile: false,
     default_profile: true,
     default_profile_image: false,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 1,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' }
